### ISSUE TITLE
switch to multi-page

### ISSUE THREAD

**Issue by jnoller** [python/getpython3.com#1]
Need to break out the information from the single column format into sub pages for expansion. Add a right-hand side bar for navigation.

**Comment by flpvsk** [comment]
Hi! I can help with that. Do you wanna do this just like on the bootstrap site? With all &lt;h2&gt;s on the toolbar?

**Comment by jnoller** [comment]
yeah I was thinking of sticking to single page, adding the navbar and scrollspy just like in thr basic bootstrap deployment - skip multi page  breakout for now

**Comment by flpvsk** [comment]
ok, I'll do it

**Comment by jnoller** [comment]
I just got a pull request: 
https://github.com/onelson/getpython3.com

**Comment by flpvsk** [comment]
that's fast!

**Comment by jnoller** [comment]
No kidding! Want to help with anything else? And I mean anything!

**Comment by flpvsk** [comment]
Of course! Let me know, what I can do, and I'll watch for new issues in this repo.

**Comment by jnoller** [comment]
Oh man that means I need to file all my ideas!

**Comment by flpvsk** [comment]
Start with a few, let's see where it goes =)

**Comment by jnoller** [comment]
Skipping this for now
