### ISSUE TITLE
Current release is Python 3.4

### ISSUE THREAD

**Issue by cclauss** [python/getpython3.com#26]
The site currently says that Python 3.3.5 is current.

**Comment by cclauss** [comment]
Given the changes made in https://github.com/jnoller/getpython3.com/commit/1337f91741b26850aec01af04ea328ec6e9dcce9 and https://github.com/jnoller/getpython3.com/commit/61b7f0317ada03b96788d8c363f1f202cd17a04f , what other edits are required before the site is updated to point visitors to Python 3.4?

**Comment by jnoller** [comment]
Hrm. I merged and deployed the changes; not sure why they're not displaying

**Comment by jnoller** [comment]
oh. git pull that works too :poop:
